services:
  - type: web
    name: crud-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn crud_backend_django.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_ALLOWED_HOSTS
        value: "*"
      - key: DATABASE_URL
        fromDatabase:
          name: crud-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
    plan: free
    postDeployCommand: python manage.py migrate
    
databases:
  - name: crud-db
    plan: free
